// Code generated by goyacc -o parser.go parser.y. DO NOT EDIT.

//line parser.y:2
package parser

import __yyfmt__ "fmt"

//line parser.y:2

// Global variables for the parser
var parseResult *Node
var parseError error
var currentLexer *Lexer

//line parser.y:11
type yySymType struct {
	yys  int
	node *Node
	str  string
	pos  int
}

const K_LIKE = 57346
const K_ILIKE = 57347
const K_AND = 57348
const K_OR = 57349
const K_BETWEEN = 57350
const K_IN = 57351
const K_IS = 57352
const K_NULL = 57353
const K_NOT = 57354
const K_TRUE = 57355
const K_FALSE = 57356
const K_LEN = 57357
const K_ANY = 57358
const K_ALL = 57359
const K_SUM = 57360
const NUMERIC_LITERAL = 57361
const STRING_LITERAL = 57362
const IDENTIFIER = 57363
const DATE = 57364
const RFC3339 = 57365
const LPAREN = 57366
const RPAREN = 57367
const COMMA = 57368
const PLUS = 57369
const MINUS = 57370
const STAR = 57371
const SLASH = 57372
const PERCENT = 57373
const LBRACKET = 57374
const RBRACKET = 57375
const EQ = 57376
const NE = 57377
const LT = 57378
const LE = 57379
const GT = 57380
const GE = 57381
const REQ = 57382
const RNE = 57383
const UMINUS = 57384

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"K_LIKE",
	"K_ILIKE",
	"K_AND",
	"K_OR",
	"K_BETWEEN",
	"K_IN",
	"K_IS",
	"K_NULL",
	"K_NOT",
	"K_TRUE",
	"K_FALSE",
	"K_LEN",
	"K_ANY",
	"K_ALL",
	"K_SUM",
	"NUMERIC_LITERAL",
	"STRING_LITERAL",
	"IDENTIFIER",
	"DATE",
	"RFC3339",
	"LPAREN",
	"RPAREN",
	"COMMA",
	"PLUS",
	"MINUS",
	"STAR",
	"SLASH",
	"PERCENT",
	"LBRACKET",
	"RBRACKET",
	"EQ",
	"NE",
	"LT",
	"LE",
	"GT",
	"GE",
	"REQ",
	"RNE",
	"UMINUS",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:167

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 118

var yyAct = [...]int8{
	6, 2, 8, 46, 47, 48, 86, 44, 45, 87,
	85, 5, 92, 49, 50, 51, 52, 53, 7, 4,
	56, 28, 38, 39, 57, 95, 42, 43, 41, 59,
	40, 62, 63, 64, 65, 66, 67, 68, 69, 70,
	71, 61, 29, 78, 79, 93, 44, 45, 60, 82,
	83, 84, 30, 31, 32, 33, 34, 35, 36, 37,
	76, 77, 58, 80, 81, 19, 44, 45, 15, 3,
	9, 25, 26, 88, 89, 90, 91, 20, 21, 22,
	24, 23, 18, 1, 0, 17, 16, 54, 55, 94,
	27, 0, 0, 0, 96, 0, 97, 10, 25, 26,
	11, 12, 13, 14, 20, 21, 22, 24, 23, 18,
	72, 73, 17, 16, 74, 75, 0, 27,
}

var yyPact = [...]int16{
	85, -1000, -1000, 14, 36, 18, -20, -26, -1000, -1000,
	85, 85, 85, 85, 85, -1000, 58, 58, 85, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 85, 85, 85,
	85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
	106, 49, 85, 85, 85, 85, 85, 85, 85, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -15, -27, -17, -1000,
	36, 18, -20, -20, -20, -20, -20, -20, -20, -20,
	-20, -20, 85, 85, 85, 85, -1000, 1, 39, -20,
	-26, -26, -1000, -1000, -1000, -1000, -1000, 85, -20, -20,
	19, -20, -1000, 85, -1000, 85, -20, -20,
}

var yyPgo = [...]int8{
	0, 83, 1, 69, 19, 11, 0, 18, 2, 70,
	68, 65, 62, 24,
}

var yyR1 = [...]int8{
	0, 1, 2, 3, 3, 4, 4, 5, 5, 5,
	5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
	5, 5, 5, 5, 5, 5, 6, 6, 6, 7,
	7, 7, 7, 8, 8, 8, 8, 8, 8, 9,
	9, 9, 9, 9, 11, 13, 13, 13, 12, 12,
	10, 10, 10, 10, 10, 10, 10,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 3, 1, 3, 1, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 4, 4,
	3, 4, 5, 6, 3, 4, 1, 3, 3, 1,
	3, 3, 3, 1, 2, 2, 2, 2, 2, 1,
	2, 2, 3, 1, 3, 0, 1, 2, 1, 3,
	1, 1, 1, 1, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, -4, -5, -6, -7, -8, -9,
	12, 15, 16, 17, 18, -10, 28, 27, 24, -11,
	19, 20, 21, 23, 22, 13, 14, 32, 7, 6,
	34, 35, 36, 37, 38, 39, 40, 41, 4, 5,
	12, 10, 8, 9, 27, 28, 29, 30, 31, -8,
	-8, -8, -8, -8, -9, -9, -2, -13, -12, -2,
	-4, -5, -6, -6, -6, -6, -6, -6, -6, -6,
	-6, -6, 4, 5, 8, 9, 11, 12, -6, -6,
	-7, -7, -8, -8, -8, 25, 33, 26, -6, -6,
	-6, -6, 11, 6, -2, 6, -6, -6,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 3, 5, 7, 26, 29, 33,
	0, 0, 0, 0, 0, 39, 0, 0, 0, 43,
	50, 51, 52, 53, 54, 55, 56, 45, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 34,
	35, 36, 37, 38, 40, 41, 0, 0, 46, 48,
	4, 6, 8, 9, 10, 11, 12, 13, 14, 15,
	16, 17, 0, 0, 0, 0, 20, 0, 0, 24,
	27, 28, 30, 31, 32, 42, 44, 47, 18, 19,
	0, 25, 21, 0, 49, 0, 22, 23,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:48
		{
			parseResult = yyDollar[1].node
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:57
		{
			yyVAL.node = NewBinaryOpNode(OpOr, yyDollar[1].node, yyDollar[3].node, yyDollar[1].node.Position)
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:62
		{
			yyVAL.node = NewBinaryOpNode(OpAnd, yyDollar[1].node, yyDollar[3].node, yyDollar[1].node.Position)
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:67
		{
			yyVAL.node = NewBinaryOpNode(OpEQ, yyDollar[1].node, yyDollar[3].node, yyDollar[1].node.Position)
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:68
		{
			yyVAL.node = NewBinaryOpNode(OpNE, yyDollar[1].node, yyDollar[3].node, yyDollar[1].node.Position)
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:69
		{
			yyVAL.node = NewBinaryOpNode(OpLT, yyDollar[1].node, yyDollar[3].node, yyDollar[1].node.Position)
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:70
		{
			yyVAL.node = NewBinaryOpNode(OpLE, yyDollar[1].node, yyDollar[3].node, yyDollar[1].node.Position)
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:71
		{
			yyVAL.node = NewBinaryOpNode(OpGT, yyDollar[1].node, yyDollar[3].node, yyDollar[1].node.Position)
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:72
		{
			yyVAL.node = NewBinaryOpNode(OpGE, yyDollar[1].node, yyDollar[3].node, yyDollar[1].node.Position)
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:73
		{
			yyVAL.node = NewBinaryOpNode(OpREQ, yyDollar[1].node, yyDollar[3].node, yyDollar[1].node.Position)
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:74
		{
			yyVAL.node = NewBinaryOpNode(OpRNE, yyDollar[1].node, yyDollar[3].node, yyDollar[1].node.Position)
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:75
		{
			yyVAL.node = NewBinaryOpNode(OpLike, yyDollar[1].node, yyDollar[3].node, yyDollar[1].node.Position)
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:76
		{
			yyVAL.node = NewBinaryOpNode(OpILike, yyDollar[1].node, yyDollar[3].node, yyDollar[1].node.Position)
		}
	case 18:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:77
		{
			likeExpr := NewBinaryOpNode(OpLike, yyDollar[1].node, yyDollar[4].node, yyDollar[1].node.Position)
			yyVAL.node = NewUnaryOpNode(OpNot, likeExpr, yyDollar[1].node.Position)
		}
	case 19:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:81
		{
			ilikeExpr := NewBinaryOpNode(OpILike, yyDollar[1].node, yyDollar[4].node, yyDollar[1].node.Position)
			yyVAL.node = NewUnaryOpNode(OpNot, ilikeExpr, yyDollar[1].node.Position)
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:85
		{
			yyVAL.node = NewBinaryOpNode(OpIs, yyDollar[1].node, NewNullNode(yyDollar[1].node.Position), yyDollar[1].node.Position)
		}
	case 21:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:86
		{
			isNullExpr := NewBinaryOpNode(OpIs, yyDollar[1].node, NewNullNode(yyDollar[1].node.Position), yyDollar[1].node.Position)
			yyVAL.node = NewUnaryOpNode(OpNot, isNullExpr, yyDollar[1].node.Position)
		}
	case 22:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:90
		{
			rangeArray := NewArrayNode([]*Node{yyDollar[3].node, yyDollar[5].node}, yyDollar[3].node.Position)
			yyVAL.node = NewBinaryOpNode(OpBetween, yyDollar[1].node, rangeArray, yyDollar[1].node.Position)
		}
	case 23:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:94
		{
			rangeArray := NewArrayNode([]*Node{yyDollar[4].node, yyDollar[6].node}, yyDollar[4].node.Position)
			betweenExpr := NewBinaryOpNode(OpBetween, yyDollar[1].node, rangeArray, yyDollar[1].node.Position)
			yyVAL.node = NewUnaryOpNode(OpNot, betweenExpr, yyDollar[1].node.Position)
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:99
		{
			yyVAL.node = NewBinaryOpNode(OpIn, yyDollar[1].node, yyDollar[3].node, yyDollar[1].node.Position)
		}
	case 25:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:100
		{
			inExpr := NewBinaryOpNode(OpIn, yyDollar[1].node, yyDollar[4].node, yyDollar[1].node.Position)
			yyVAL.node = NewUnaryOpNode(OpNot, inExpr, yyDollar[1].node.Position)
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:108
		{
			yyVAL.node = NewBinaryOpNode(OpPlus, yyDollar[1].node, yyDollar[3].node, yyDollar[1].node.Position)
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:109
		{
			yyVAL.node = NewBinaryOpNode(OpMinus, yyDollar[1].node, yyDollar[3].node, yyDollar[1].node.Position)
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:114
		{
			yyVAL.node = NewBinaryOpNode(OpStar, yyDollar[1].node, yyDollar[3].node, yyDollar[1].node.Position)
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:115
		{
			yyVAL.node = NewBinaryOpNode(OpSlash, yyDollar[1].node, yyDollar[3].node, yyDollar[1].node.Position)
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:116
		{
			yyVAL.node = NewBinaryOpNode(OpPercent, yyDollar[1].node, yyDollar[3].node, yyDollar[1].node.Position)
		}
	case 34:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:121
		{
			yyVAL.node = NewUnaryOpNode(OpNot, yyDollar[2].node, yyDollar[2].node.Position)
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:122
		{
			yyVAL.node = NewUnaryOpNode(OpLen, yyDollar[2].node, yyDollar[2].node.Position)
		}
	case 36:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:123
		{
			yyVAL.node = NewUnaryOpNode(OpAny, yyDollar[2].node, yyDollar[2].node.Position)
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:124
		{
			yyVAL.node = NewUnaryOpNode(OpAll, yyDollar[2].node, yyDollar[2].node.Position)
		}
	case 38:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:125
		{
			yyVAL.node = NewUnaryOpNode(OpSum, yyDollar[2].node, yyDollar[2].node.Position)
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:130
		{
			yyVAL.node = NewUnaryOpNode(OpUMinus, yyDollar[2].node, yyDollar[2].node.Position)
		}
	case 41:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:131
		{
			yyVAL.node = yyDollar[2].node
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:132
		{
			yyVAL.node = yyDollar[2].node
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:133
		{
			yyVAL.node = yyDollar[1].node
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:137
		{
			yyVAL.node = yyDollar[2].node
		}
	case 45:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:141
		{
			yyVAL.node = NewArrayNode([]*Node{}, 0)
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:142
		{
			yyVAL.node = yyDollar[1].node
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:143
		{
			yyVAL.node = yyDollar[1].node
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:147
		{
			yyVAL.node = NewArrayNode([]*Node{yyDollar[1].node}, yyDollar[1].node.Position)
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:150
		{
			// Append to existing array
			yyDollar[1].node.Children = append(yyDollar[1].node.Children, yyDollar[3].node)
			yyVAL.node = yyDollar[1].node
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:158
		{
			yyVAL.node = NewNumberNode(yyDollar[1].str, yyDollar[1].pos)
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:159
		{
			yyVAL.node = NewStringNode(yyDollar[1].str, yyDollar[1].pos)
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:160
		{
			yyVAL.node = NewIdentifierNode(yyDollar[1].str, yyDollar[1].pos)
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:161
		{
			yyVAL.node = NewTimestampNode(yyDollar[1].str, yyDollar[1].pos)
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:162
		{
			yyVAL.node = NewDateNode(yyDollar[1].str, yyDollar[1].pos)
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:163
		{
			yyVAL.node = NewBooleanNode(true, yyDollar[1].pos)
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:164
		{
			yyVAL.node = NewBooleanNode(false, yyDollar[1].pos)
		}
	}
	goto yystack /* stack new state and value */
}
